### PR TITLE
Change old URLS

### PR DESCRIPTION
**Pull request by masteradhoc**
Not tested all urls, just the ones i direclty saw and used that needed a change.

### CODE REVIEW

**Comment by masteradhoc** [comment]
@shadimanna could anyone check this PR and get back to my request i shared over email?

**Comment by Abdalsalaam** [comment]
@masteradhoc thank you for updating this

**Comment by masteradhoc** [comment]
@Abdalsalaam thanks! Can u check also the php warnings issues task i created?

**Comment by Abdalsalaam** [comment]
@masteradhoc sure! thank you

**Pull request merged**
